#!/bin/sh /etc/rc.common

# put the script into /etc/init.d 
# and perform: /etc/init.d/button_slider enable
# the slider config is for MR3040 v2
# if your device is MR3020 then swap sw2 and sw1

START=19
boot() {

if grep -qe "sw2.*in.*hi" /sys/kernel/debug/gpio ; then
  if grep -qe "sw1.*in.*hi" /sys/kernel/debug/gpio ; then
	# AP
	logger "slider in AP position"
	/ow2/set_network_config.sh /ow2/settings.pvt AP
  else
	# 3G
	logger "slider in 3G position"
	/ow2/set_network_config.sh /ow2/settings.pvt 3G
  fi
else
	# WISP
	logger "slider in WISP position"
	/ow2/set_network_config.sh /ow2/settings.pvt WISP
fi
}

