#!/bin/sh

# put the script into /etc/hotplug.d/button

if [ -f /tmp/slider_waiting_state ]; then exit 0
fi

touch /tmp/slider_waiting_state
sleep 1

if [ $BUTTON = 'BTN_0' ] || [ $BUTTON = 'BTN_1' ]; then 
  logger "slider event:"
  rm  /tmp/slider_waiting_state
  if grep -qe "sw2.*in.*hi" /sys/kernel/debug/gpio ; then
    if grep -qe "sw1.*in.*hi" /sys/kernel/debug/gpio ; then
	# AP
	logger "slider now in AP position"
	/ow2/set_network_config.sh /ow2/settings.pvt AP
    else
	# 3G
	logger "slider now in 3G position"
	/ow2/set_network_config.sh /ow2/settings.pvt 3G
    fi
    /etc/init.d/network reload
    wifi
  else
	# WISP
	logger "slider now in WISP position"
	/ow2/set_network_config.sh /ow2/settings.pvt WISP
	/etc/init.d/network reload
	sleep 1
	wifi
  fi
fi
